apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
    - name: shell
      command: ["sleep", "infinity"]
      image: debian
      volumeMounts:
      - name: volume
        mountPath: /volume
  volumes:
    - name: volume
      hostPath:
        path: /tmp/data 
      