apiVersion: v1
kind: Service
metadata:
  name: chatapp-fullstack-service
spec:
  selector:
    app: chatapp-fullstack
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      name: chatapp-frontend
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: chatapp-backend
  type: NodePort