apiVersion: v1
kind: Pod
metadata:
  name: test-communication
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["sleep", "infinity"]
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
    
